site_name: کیت پایتونی ایتا

theme:
  name: 'material'
  language: 'fa'
  direction: 'rtl'
  palette:
    primary: 'orange'
    accent: 'orange'
  font: false
  feature:
    tabs: false
  extra:
    social:
      - type: 'github'
        link: 'https://github.com/bistcuite'    
  features:
    - content.code.copy
    - content.code.select
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - 'stylesheets/extra.css'

nav:
- مستندات: 'index.md'
- مخزن گیت‌هاب: 'https://github.com/bistcuite/eitaapykit'
- PyPI: 'https://pypi.org/project/eitaa'
- سایت ایتایار: 'https://eitaayar.ir'
- وبسایت رسمی ایتا: 'https://eitaa.com'
- نسخۀ وب ایتا: 'https://web.eitaa.com'